name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/**.md'
      - '.github/**'

jobs:
  publish:
    name: Publish the app
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    
    - name: Publish
      shell: pwsh
      run: |
        Set-Location "$env:GITHUB_WORKSPACE"
        MSBuild Dumper-7.sln /p:configuration=Release /p:platform=x64
        ls
